recipes['Spicy Ginger Metheglin (1gal.)'] = {
    type: 'Spicy Ginger Metheglin (1gal.)',
    volume: '1 gal',
    brewTime: [
        '3 week primary',
        '2 month (or to taste) secondary',
        '2 week stabilization/clarifying',
    ],
    ingredients: [
        '3.5 lbs honey',
        '1 tsp LD Carlson Nutrient (diammonium phosphate/DAP)',
        '0.5 tsp LD Carlson Energizer (yeast hulls)',
        '5 grams Lavlin 71B-1122',
        'Spring or tap water to 1 gal.',
        '1 lb raw ginger, peeled and cubed',
        'Xylitol to taste (optional)',
    ],
    equipmentMisc: [
        '1 gal. carboy',
        'Airlock',
        'StarSan soln.',
        '1 Campden tablet, crushed',
        '0.5 tsp potassium sorbate',
        '1.5 tbsp hydrated (2 tsp in .5 cup very hot water, agitate thoroughly, rest for 12 hours) bentonite slurry or Sparkoloid per label (optional)',
        'Autosiphon/wine thief/hydrometer',
    ],
    recipe: [
        'Clean 1 gal. carboy with StarSan soln.; .1oz starsan (.6 tsp) for half gallon. Let sit for three minutes, then rinse until suds subside.',
        'Add room temperature honey then room temperature spring or tap water until volume of must is shy of 1 gal.',
        'Pour dry yeast into must and add DAP with yeast hulls.',
        'Seal carboy and shake vigorously for 4 minutes. SG check.',
        'Fill to 1 gal., put into carboy, and airlock. Place in dark location at 60 - 75 degrees F.',
        'After one month, rack onto peeled and cubed ginger. SG check.',
        'After two months (or to taste) on ginger, rack off lees onto crushed Campden tablet, potassium sorbate, and, optionally, clarifying agent (Sparkoloid or bentonite). SG check. After two weeks or when clear, optionally backsweeten with xylitol and bottle.',
    ],
    fdaIngredients: 'water, raw organic honey, yeast, ginger, less than 0.5% of the following: yeast nutrients (diammonium phosphate, yeast ghosts), potassium metabisulfate, potassium sorbate, bentonite, flavor from organic ginger',
};
