recipes['Reaper Capsicumel (1gal.)'] = {
    type: 'Reaper Capsicumel (1gal.)',
    volume: '1 gal',
    brewTime: [
        '1 month primary',
        '1 month oaking/secondary',
        '2 week stabilization',
    ],
    ingredients: [
        '3 lbs honey',
        '1 tsp LD Carlson Nutrient (diammonium phosphate/DAP)',
        '0.5 tsp LD Carlson Energizer (yeast hulls)',
        '5 grams Safale US-05',
        '4 Carolina Reaper chilis',
        '1 Med. toast oak spiral',
        'Spring or tap water to 1 gal.',
        'Xylitol to taste (optional)',
    ],
    equipmentMisc: [
        '1 gal. carboy',
        'Airlock',
        'StarSan soln.',
        '1 Campden tablet, crushed',
        '0.5 tsp potassium sorbate',
        '1.5 tbsp hydrated (2 tsp in .5 cup very hot water, agitate thoroughly, rest for 12 hours) bentonite slurry or Sparkoloid per label (optional)',
    ],
    recipe: [
        'Clean 1 gal. carboy with StarSan soln.; .1oz starsan (.6 tsp) for half gallon. Let sit for three minutes, then rinse until suds subside.',
        'Add room temperature honey, then room temperature spring or tap water until volume of must is short of 1 gal. Pour dry yeast into must and add DAP with yeast hulls.',
        'Seal carboy and shake vigorously for 4 minutes.',
        'SG check.',
        'Simmer chopped and de-seeded chilis in 1/4 cup of water for ten minutes; pour into must through muslin and tie off muslin.',
        'Fill with water to 1 gal. Airlock carboy.',
        'Place in dark location at 60 - 75 degrees F.',
        'After 1 month, rack off peppers and into new vessel with oak spiral. SG check.',
        'After another month, rack off oak onto crushed Campden tablet, potassium sorbate, and, optionally, clarifying agent (Sparkoloid or bentonite). SG check. After a two weeks or when clear, optionally backsweeten with xylitol and bottle.',
    ],
    fdaIngredients: 'water, raw organic honey, yeast, xylitol, less than 0.5% of the following: yeast nutrients (diammonium phosphate, yeast ghosts), potassium metabisulfate, potassium sorbate, bentonite, flavor from oak wood and organic carolina reaper chili',
};
