recipes['Sweet Metheglin (1gal.)'] = {
    type: 'Sweet Metheglin (1gal.)',
    volume: '1 gal',
    brewTime: [
        '2 week primary',
        '2 week secondary',
        '1 week stabilization/clarifying',
    ],
    ingredients: [
        '3.5 lbs honey',
        '1 tsp LD Carlson Nutrient (diammonium phosphate/DAP)',
        '0.5 tsp LD Carlson Energizer (yeast hulls)',
        '5 grams Safale US-05 yeast',
        '1 vanilla bean',
        '1 cinnamon stick',
        'Spring or tap water to 1 gal.',
    ],
    equipmentMisc: [
        '1 gal. carboy',
        'Airlock',
        'StarSan soln.',
        '1 Campden tablet, crushed',
        '0.5 tsp potassium sorbate',
        '1.5 tbsp hydrated (2 tsp in .5 cup very hot water, agitate thoroughly, rest for 12 hours) bentonite slurry or Sparkoloid per label (optional)',
    ],
    recipe: [
        'Clean 1 gal. carboy with StarSan soln.; .1oz starsan (.6 tsp) for half gallon. Let sit for three minutes, then rinse until suds subside.',
        'Boil vanilla bean and cinnamon stick in 1 cup water for 10 minutes.',
        'Add room temperature honey then room temperature spring or tap water until volume of must is 1 gal.',
        'Pour dry yeast into must, add cinnamon and vanilla with water, and add DAP with yeast hulls.',
        'Seal carboy and shake vigorously for 4 minutes. SG check. Airlock carboy.',
        'Place in dark location at 60 - 75 degrees F.',
        'After two weeks, rack off lees into sanitized carboy.',
        'After two more weeks, rack onto crushed Campden tablet, potassium sorbate, and, optionally, clarifying agent (Sparkoloid or bentonite). SG check. After a week or when clear, bottle.',
    ],
    fdaIngredients: 'water, raw organic honey, yeast, less than 0.5% of the following: yeast nutrients (diammonium phosphate, yeast ghosts), potassium metabisulfate, potassium sorbate, bentonite, flavor from organic cinnamon and vanilla',
};
